FROM twdps/di-circleci-remote-docker:slim-2021.07

LABEL maintainer=<nchenewe@thoughtworks.com>

ENV CONFTEST_VERSION=0.25.0
ENV CHAMBER_VERSION=2.10.1

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

# hadolint ignore=DL3004,SC2035
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90circleci && \
	echo 'DPkg::Options "--force-confnew";' >> /etc/apt/apt.conf.d/90circleci && \
    echo "deb [trusted=yes] https://apt.secrethub.io stable main" > /etc/apt/sources.list.d/secrethub.sources.list && apt-get update && \
    apt-get install --no-install-recommends -y \
            sudo=1.8.27-1+deb10u3 \
            locales=2.28-10 \
            curl=7.64.0-4+deb10u2 \
            wget=1.20.1-1.1 \
            gnupg=2.2.12-1+deb10u1 \
            jq=1.5+dfsg-2+b1 \
            secrethub-cli=0.42.1 \
            apt-transport-https=1.8.2.3 \
            lsb-release=10.2019051400 && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && apt-get install --no-install-recommends -y \        
            docker-ce=5:20.10.7~3-0~debian-buster \
            docker-ce-cli=5:20.10.7~3-0~debian-buster \
            containerd.io=1.4.6-1 && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install --no-install-recommends -y \
            nodejs=14.17.2-1nodesource1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen && \
    sudo npm install -g \
             snyk@1.653.0 \
             bats@1.3.0 && \
    sudo wget https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz && \
    sudo tar xzf conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz && \
    sudo mv conftest /usr/local/bin && sudo rm conftest* && \
    sudo curl -LOs https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-linux-amd64 && \
    sudo chmod +x chamber-v${CHAMBER_VERSION}-linux-amd64 && \
    sudo mv chamber-v${CHAMBER_VERSION}-linux-amd64 /usr/local/bin/chamber && \
    useradd --uid=3434 --user-group --create-home circleci && usermod --shell /bin/bash circleci && \
    echo 'circleci ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    sudo -u circleci mkdir /home/circleci/project && \
    sudo -u circleci mkdir /home/circleci/.gnupg && \
    echo 'allow-loopback-pinentry' > /home/circleci/.gnupg/gpg-agent.conf && \
    echo 'pinentry-mode loopback' > /home/circleci/.gnupg/gpg.conf && \
    chmod 700 /home/circleci/.gnupg && chmod 600 /home/circleci/.gnupg/*

ENV PATH=/home/circleci/bin:/home/circleci/.local/bin:$PATH \
	LANG=en_US.UTF-8 \
	LANGUAGE=en_US:en \
	LC_ALL=en_US.UTF-8

USER circleci

WORKDIR /home/circleci/project
