---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@dev:e16463c
  snyk: snyk/snyk@0.0.10

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  di-circleci-base-image-pipeline:
    jobs:
      - executor-tools/dev-release:
          name: "dev-build"
          context: twdps-di
          image: twdps/di-circleci-base-image
          tag: edge
          docker-cve-scan: true
          snyk-organization: twdps
          # after-build:
          #   - run:
          #       command: |
          #         docker run -it \
          #                    -e "SNYK_TOKEN=<$SNYK_TOKEN" \
          #                    -e "MONITOR=false" \
          #                    -v "${PWD}:/project" \
          #                    -v "/var/run/docker.sock:/var/run/docker.sock" \
          #                    snyk/snyk-cli:docker test --docker twdps/di-circleci-base-image:dev.$CIRCLE_SHA1 --file=./Dockerfile
            # - snyk/scan:
            #     docker-image-name: twdps/di-circleci-base-image:dev.$CIRCLE_SHA1
            #     organization: twdps
            #     fail-on-issues: true
            #     monitor-on-build: false
          filters: *on-push-master
          
      - executor-tools/publish:
          name: Release
          context: twdps-di
          image: twdps/di-circleci-base-image
          release: stable
          clean-tags:
            - executor-tools/clean-docker-hub:
                image: twdps/di-circleci-base-image
          filters: *on-tag-master
          
