---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@0.4.1
  snyk: snyk/snyk@0.0.10

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  di-circleci-base-image-pipeline:
    jobs:
      - executor-tools/dev-release:
          name: "dev-build"
          context: ZTW
          after_build:
            - snyk/scan:
                docker-image-name: twdps/di-circleci-base-image:$CIRCLE_SHA1
                organization: twdps
                fail-on-issues: true
                monitor-on-build: false
          filters: *on-push-master
          image: twdps/di-circleci-base-image
      - executor-tools/publish:
          name: Release
          context: ZTW
          clean-tags:
              - clean-quay:
                  image: twdps/di-circleci-base-image
          filters: *on-tag-master
          image: twdps/di-circleci-base-image
