---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@dev:latest

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  di-circleci-base-alpine-image-pipeline:
    jobs:
      - executor-tools/machine-executor-dev-release:
          name: alpine-dev-build
          context: twdps-di
          dockerfile: Dockerfile.alpine
          image: twdps/di-circleci-base-image
          tag: alpine-edge
          docker-cve-scan: true
          snyk-organization: twdps
          cis-docker-image-scan: true
          skip-base-image: true
          bats-test: true
          test-path: test/di_circleci_base_image_alpine.bats
          container-name: di-circleci-base-image-alpine-edge
          filters: *on-push-master
          
      - executor-tools/publish:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: alpine-release
          context: twdps-di
          pull-tag: alpine-edge
          tag-annotation: alpine-
          image: twdps/di-circleci-base-image
          release-tag: alpine-stable
          filters: *on-tag-master        

  di-circleci-base-slim-image-pipeline:
    jobs:
      - executor-tools/dev-release:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: slim-dev-build
          context: twdps-di
          dockerfile: Dockerfile.slim
          image: twdps/di-circleci-base-image
          tag: slim-edge
          bats-test: true
          test-path: test/di_circleci_base_image_slim.bats
          container-name: di-circleci-base-image-slim-edge
          filters: *on-push-master
          
      - executor-tools/publish:
          shell: secrethub run -- /bin/sh -eo pipefail
          name: slim-release
          context: twdps-di
          pull-tag: slim-edge
          tag-annotation: slim-
          image: twdps/di-circleci-base-image
          release-tag: slim-stable
          filters: *on-tag-master  

  # NOTE: currently circleci does not support scheduled builds that use restricted contexts
  # builds nightly from .unpinned Dockerfile in order to test the latest base image and installed packages
  # di-circleci-base-image-nightly-build:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * 0"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - executor-tools/dev-release:
  #         shell: secrethub run -- /bin/sh -eo pipefail
  #         name: "nightly-build"
  #         context: twdps-di
  #         image: twdps/di-circleci-base-image
  #         tag: nightly
  #         dockerfile: Dockerfile.alpine.unpinned
  #         snyk-organization: twdps
  #         skip-base-image: true
  #         cis-docker-image-scan: true
  #         bats-test: true
  #         test-path: test/di_circleci_base_image_alpine.bats
  #         container-name: di-circleci-base-image-alpine-edge
